#!/usr/bin/env python

import os
import json
import sys

tomount   = {}
erreure   = 0

for distrib in os.listdir("../distrib"):
	if distrib == "windows":
		continue
	try:
		with open("../distrib/" + distrib + "/param.json") as setting:
			tomount[distrib] = "../distrib/" + distrib + "/" + json.loads(setting.read())["image"]
	except Exception, e:
		print("erreure: fichier manquant: distrib/" + distrib + "/param.json")
		erreure += 1

for name,iso in tomount.items():
	try:
		if not os.path.exists("mounted/" + name):
			os.makedirs("mounted/" + name)
		oups = os.system("mount -o loop " + iso + " mounted/" + name)
		if oups:
			print("erreure: " + name + ": iso non monte")
			erreure += 1
		else:
			print(name + " a bien ete monte")
	except Exception, e:	
		print(e)
		erreure += 1

sys.exit(erreure)