#!/usr/bin/env python

import os
import json


path    = json.loads(open("/etc/ipexpress/settings.json").read())["path"]
tomount = {}
erreure = 0

for distrib in os.listdir(path + "distrib"):
	if distrib == "windows":
		# TODO windows
		continue
	try:
		with open(path + "distrib/" + distrib + "/param.json") as setting:
			tomount[distrib] = path + "distrib/" + distrib + "/" + json.loads(setting.read())["image"]
	except Exception, e:
		print("erreure: fichier manquant: " + path  + "distrib/" + distrib + "/param.json")
		erreure += 1

for name,iso in tomount.items():
	try:
		if not os.path.exists(path + "nfs/mounted/" + name):
			os.makedirs(path + "nfs/mounted/" + name)
		oups = os.system("mount -o loop " + iso + " " + path + "nfs/mounted/" + name)
		if oups:
			print("erreure: " + name + ": iso non monte")
			erreure += 1
		else:
			print(name + " a bien ete monte")
	except Exception, e:	
		print(e)
		erreure += 1

if erreure!=0 :
	print("doc: https://github.com/Ricain/ipexpress/wiki/mount#erreurs")
exit(erreure)