#!/usr/bin/env python

import os
import json

settings = json.loads(open("/etc/ipexpress/settings.json").read())
path     = settings["path"]
nfsd     = settings["nfs-server-name"]
erreure  = 0

for distrib in os.listdir(path + "nfs/mounted"):
	if distrib == "README.md":
		continue
	try:
		print("demontage de " + distrib)
		oups = os.system("umount -l " + path + "nfs/mounted/" + distrib)
		if oups:
			erreure += 1
		else :
			oups = os.rmdir(path + "nfs/mounted/" + distrib)
			if oups:
				erreure += 1
				continue
		print("suppression de " + distrib + " de /etc/exports")
		nfs_config = open("/etc/exports", "r")
		config = nfs_config.readlines()
		nfs_config.close()
		nfs_config = open("/etc/exports", "w")
		for line in config:
			if  path + "nfs/mounted/" + distrib in line or line=="\n":
				continue
			nfs_config.write(line)
		nfs_config.close()
	except Exception, e:
		print(e)
		continue

oups = os.system("service " + nfsd + " restart")
if oups:
	erreure += 1

if erreure!=0:
	print("doc: https://github.com/Ricain/ipexpress/wiki/umount");
	
exit(erreure)