#!/usr/bin/env python

import os
import json

path    = json.loads(open("/etc/ipexpress/settings.json").read())["path"]
erreure = 0

for distrib in os.listdir(path + "nfs/mounted"):
	if distrib == "README.md":
		continue
	try:
		oups = os.system("umount " + path + "nfs/mounted/" + distrib)
		if oups:
			erreure += 1
		oups = os.rmdir(path + "nfs/mounted/" + distrib)
		if oups:
			erreure += 1
	except Exception, e:
		print(e)
		continue

if erreure!=0:
	print("doc: https://github.com/Ricain/ipexpress/wiki/umount");
	
exit(erreure)