#!/usr/bin/env python

import sys
import os
import json
import signal

def ctrlc(signal, frame):
	print("")
	exit(10)

signal.signal(signal.SIGINT,ctrlc)

# traitement des argument

if len(sys.argv) <= 1:
	print("erreur: 1: je ne sais pas quoi faire (argument manquant)")
	print("doc   : https://github.com/Ricain/ipexpress/wiki/build#1")
	exit(1)

if sys.argv[1] != "cd" and sys.argv[1] != "usb":
	print("erreur: 2: je ne sais pas comment construire " + sys.argv[1] + "! (mauvais argument)")
	print("doc   : https://github.com/Ricain/ipexpress/wiki/build#2")
	exit(2)

if len(sys.argv) >= 3:
	if not os.path.exists(sys.argv[2]):
		print("erreur: " + sys.argv[2] + ": 3: media inconnu")
		print("doc   : https://github.com/Ricain/ipexpress/wiki/build#3")
		exit(3)

# recupereation des paramettres genereaux

try:
	with open("/etc/ipexpress/settings.json","r") as fsetting:
		settings = json.loads(fsetting.read())
except Exception as e:
	print("erreur: 4: lecture du fichier de config impossible: " + str(e))
	print("doc   : https://github.com/Ricain/ipexpress/wiki/build#4")
	exit(4)

# creation du script embed

try:
	embed = open(settings["path"] + "boot/embed.ipxe","w")
	embed.write("#!ipxe\n\n")
	embed.write("dhcp\nlogin\n")
	embed.write("chain http://${username:uristring}:${password:uristring}@" + settings["web-server"] + "/ipexpress/core/boot.php")
	embed.close()
except Exception as e:
	print("erreur: 5: impossible d'ecrire le fichier embed.ipxe: " + str(e))
	print("doc   : https://github.com/Ricain/ipexpress/wiki/build#5")
	exit(5)

# compilation de l'image

try:
	if sys.argv[1] == "cd":
		ext = "iso"
	else:
		ext = "usb"
	oups = os.system("cd " + settings["path"] + "boot/ipxe/src; make clean; make bin/ipxe." + ext + " EMBED=../../embed.ipxe && mv bin/ipxe." + ext + " ../.. ; make clean")
	if not os.path.exists(settings["path"] + "boot/ipxe." + ext):
		print("erreur: 6: probleme de compilation")
		print("doc   : https://github.com/Ricain/ipexpress/wiki/build#6-et-7")
		exit(6)
except Exception as e:
	print("erreur: 7: probleme de compilation: " + str(e))
	print("doc   : https://github.com/Ricain/ipexpress/wiki/build#6-et-7")
	exit(7)
print("image cree")

# copie de l'image dans un media

if len(sys.argv) >= 3:
	os.system("dd if=" + settings["path"] + "boot/ipxe." + ext + " of=" + sys.argv[2])
