#!/usr/bin/env python

import sys
import os
import json
import signal

def ctrlc(signal, frame):
	print("")
	exit(10)

signal.signal(signal.SIGINT,ctrlc)

if len(sys.argv) <= 1:
	print("erreure: je ne sais pas quoi faire (argument manquant)\ndoc: https://google.com")
	exit(1)

if sys.argv[1] != "cd" and sys.argv[1] != "usb":
	print("erreure: je ne sais pas comment construire " + sys.argv[1] + "! (mauvais argument)\ndoc: https://google.com")
	exit(2)

if len(sys.argv) >= 3:
	if not os.path.exists(sys.argv[2]):
		print("erreure: " + sys.argv[2] + ": media inconnu\ndoc: https://google.com")
		exit(3)

try:
	with open("../settings.json","r") as fsetting:
		settings = json.loads(fsetting.read())
except Exception, e:
	print("erreure: lecture du fichier de config impossible: " + str(e))
	exit(4)

try:
	embed = open("embed.ipxe","w")
	embed.write("#!ipxe\n\n")
	embed.write("dhcp\n")
	embed.write("chain http://" + settings["web-server"] + "/ipexpress/core/boot.php")
	embed.close()
except Exception, e:
	print("erreure: impossible d'ecrire le fichier embed.ipxe: " + str(e))
	exit(5)

try:
	if sys.argv[1] == "cd":
		ext = "iso"
	else:
		ext = "usb"
	oups = os.system("cd ipxe/src; make clean; make bin/ipxe." + ext + " EMBED=../../embed.ipxe && mv bin/ipxe." + ext + " ../.. ; make clean")
	if not os.path.exists("ipxe." + ext):
		print ("erreure: probleme de compilation")
		exit(6)
except Exception, e:
	print ("erreure: probleme de compilation: " + str(e))
	exit(7)
print("image cree")

if len(sys.argv) >= 3:
	os.system("dd if=ipxe." + ext + " of=" + sys.argv[2])