#!/bin/sh

# WEB
ln -s /home/jean/ipexpress/dev/apache.conf /etc/apache2/conf.d/ipexpress.conf

# NFS
echo "/home/jean/ipexpress/nfs/mounted *(ro,insecure,all_squash,no_subtree_check)" | tee -a /etc/export
/home/jean/ipexpress/nfs/mount
service nfs-kernel-server restart